name: atividade
description: "Projeto Inventário Mágico SESI SENAI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Versão estável compatível

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.4
  google_fonts: ^6.2.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Configuração da imagem de fundo
  assets:
    - assets/images/fundo.png
    - assets/images/floresta.png